# Change these first
owner: juan9f # Your GitHub organization or username, where this repository lives
repo: mpsa-uptime # The name of this repository

sites:
  - name: Itris
    check: "tcp-ping"
    url: 190.210.205.89
    port: 53
  - name: GV
    check: "tcp-ping"
    url: http://rh03.rhconsult.com.ar/
  - name: Campus
    url: https://campus.manpetrolfse.com.ar/
  - name: PDM (Success Factors)
    url: https://performancemanager5.successfactors.eu/login#/login
  - name: Tu Legajo
    url: https://app.tulegajo.com/login.htm
  - name: Portal empleo
    url: https://manpetrol.hiringroom.com/jobs/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /mpsa-uptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: MPSA Estado de los Servicios
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
